apiVersion: ships.k8s.io/v1beta1
kind: Foo
metadata:
  name: should-be-fine
spec:
  image: ubuntu

---

apiVersion: ships.k8s.io/v1beta1
kind: Foo
metadata:
  name: image-dont-exist
spec:
  image: ubuntuuu
