apiVersion: ships.k8s.io/v1beta1
kind: Foo
metadata:
  name: should-be-fine
  labels:
    foo: works
spec:
  image: ubuntu

---

apiVersion: ships.k8s.io/v1beta1
kind: Foo
metadata:
  name: image-dont-exist
  labels:
    foo: fails
spec:
  image: ubuntuuu
